<a href="https://colab.research.google.com/github/Sg-11004/ADP-project-1.html/blob/main/YBIprojet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a credit assessment model for Banking and Financial sector with below given data link

In [40]:
#imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_absolute_percentage_error,confusion_matrix,classification_report



In [41]:
#read the dataset
df=pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Credit%20Default.csv')

In [42]:
df


Income        Age         Loan  Loan to Income  Default
0     66155.92510  59.017015  8106.532131        0.122537        0
1     34415.15397  48.117153  6564.745018        0.190752        0
2     57317.17006  63.108049  8020.953296        0.139940        0
3     42709.53420  45.751972  6103.642260        0.142911        0
4     66952.68885  18.584336  8770.099235        0.130990        1
...           ...        ...          ...             ...      ...
1995  59221.04487  48.518179  1926.729397        0.032535        0
1996  69516.12757  23.162104  3503.176156        0.050394        0
1997  44311.44926  28.017167  5522.786693        0.124636        1
1998  43756.05660  63.971796  1622.722598        0.037086        0
1999  69436.57955  56.152617  7378.833599        0.106267        0

[2000 rows x 5 columns]

In [43]:
df.head()

Income        Age         Loan  Loan to Income  Default
0  66155.92510  59.017015  8106.532131        0.122537        0
1  34415.15397  48.117153  6564.745018        0.190752        0
2  57317.17006  63.108049  8020.953296        0.139940        0
3  42709.53420  45.751972  6103.642260        0.142911        0
4  66952.68885  18.584336  8770.099235        0.130990        1

In [ ]:
df.columns

In [ ]:
df.describe()

In [ ]:
df.tail()

In [37]:
x=df.drop('Default',axis=1)
y=df['Default']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2529)

In [38]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [39]:
raw_sample=x_test.sample(1)
raw_sample

Income        Age         Loan  Loan to Income
25  47451.63012  27.031741  5361.282716        0.112984

In [29]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [28]:
res=model.predict(raw_sample)
res

array([0])

In [46]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.9125
Confusion Matrix:
 [[340   7]
 [ 28  25]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.98      0.95       347
           1       0.78      0.47      0.59        53

    accuracy                           0.91       400
   macro avg       0.85      0.73      0.77       400
weighted avg       0.91      0.91      0.90       400



In [49]:
def raw_pred():
  raw_sam=x_train.sample(1)
  pred=model.predict(raw_sam)
  if pred==1:
    print("Borrower defaulted his loan")
  else:
    print("Borrower hasn't defaulted his loan")
raw_pred()

Borrower hasn't defaulted his loan
